image: openjdk:17
pipelines:
  default:
    - step:
        script:
          - bash ./gradlew build
          - pwd
          - ls -lah
          - cd ~
          - ls -Rla
        artifacts: # defining the artifacts to be passed to each future step.
          - ~/build/libs/*.jar
